--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 7.0.249.0
-- Product home page: https://www.devart.com/dbforge/sql/studio
-- Script date 04/03/2025 02:24:09
-- Server version: 16.00.1000
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT, XACT_ABORT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS OFF
GO

BEGIN TRANSACTION

--
-- Inserting data into table fedeco.dbo.SchoolDim
--
INSERT fedeco.dbo.SchoolDim(school_id, full_name, school_display, state, school_website) VALUES
(1, N'Federal Government Girls'' College, Umuahia', 'FGGC Umuahia ', N'Abia', N'https://fggcumuahia.sch.ng/'),
(2, N'Federal Government College, Ohafia', 'FGC Ohafia ', N'Abia', N'https://fgcohafia.sch.ng/'),
(3, N'Federal Science and Technical College, Ohanso', 'FSTC Ohanso ', N'Abia', N'https://fstcohanso.sch.ng/'),
(4, N'Federal Government College, Nise', 'FGC Nise ', N'Anambra', N'https://fgcniseonline.sch.ng/'),
(5, N'Federal Government Girls'' College, Onitsha', 'FGGC Onitsha ', N'Anambra', N'https://fggconitshang.sch.ng/'),
(6, N'Federal Science and Technical College, Awka', 'FSTC Awka ', N'Anambra', N'https://fstcawka.sch.ng/'),
(7, N'Federal Government College, Enugu', 'FGC Enugu ', N'Enugu', N'https://fgcenugu.sch.ng/'),
(8, N'Federal Government Girls'' College, Lejja', 'FGGC Lejja ', N'Enugu', N'https://fggclejja.sch.ng/'),
(9, N'Federal Government College, Okigwe', 'FGC Okigwe ', N'Imo', N'https://fgcokigwe.sch.ng/'),
(10, N'Federal Government Girls'' College, Owerri', 'FGGC Owerri ', N'Imo', N'https://fggcowerri.sch.ng/'),
(11, N'Federal Science and Technical College, Oguta', 'FSTC Oguta ', N'Imo', N''),
(12, N'Federal Government College, Okposi', 'FGC Okposi ', N'Ebonyi', N'https://fgcokposi.sch.ng/'),
(13, N'Federal Government Girls'' College, Ezzamgbo', 'FGGC Ezzamgbo ', N'Ebonyi', N'https://fggcezzamgbo.sch.ng/'),
(14, N'Federal Science and Technical College, Amuzu', 'FSTC Amuzu ', N'Ebonyi', N'https://fstc.tungbo.sch.ng/'),
(15, N'Federal Government College, Ganye', 'FGC Ganye ', N'Adamawa', N'https://fgcganye.sch.ng/'),
(16, N'Federal Government Girls'' College, Yola', 'FGGC Yola ', N'Adamawa', N'https://fggcyola.sch.ng/'),
(17, N'Federal Science and Technical College, Michika', 'FSTC Michika ', N'Adamawa', N'https://fstcmichika.sch.ng/'),
(18, N'Federal Government College, Azare', 'FGC Azare ', N'Bauchi', N'https://fgcazare.sch.ng/'),
(19, N'Federal Government Girls'' College, Bauchi', 'FGGC Bauchi ', N'Bauchi', N'https://fggcbauchi.sch.ng/'),
(20, N'Federal Government College, Maiduguri', 'FGC Maiduguri ', N'Borno', N'https://fgcmaiduguri.sch.ng/'),
(21, N'Federal Government Girls'' College, Monguno', 'FGGC Monguno ', N'Borno', N'https://fgcmonguno.sch.ng/'),
(22, N'Federal Science and Technical College, Lassa', 'FSTC Lassa ', N'Borno', N'https://fstclassa.sch.ng/'),
(23, N'Federal Government College, Wukari', 'FGC Wukari ', N'Taraba', N'https://fgcwukari.sch.ng/'),
(24, N'Federal Government Girls'' College, Jalingo', 'FGGC Jalingo ', N'Taraba', N'http://fggcjalingo.sch.ng/'),
(25, N'Federal Science and Technical College, Jalingo', 'FSTC Jalingo ', N'Taraba', N'http://fstcjalingo.sch.ng/'),
(26, N'Federal Government College, Buni-Yadi', 'FGC Buni-Yadi ', N'Yobe', N'https://fgcbunuyadi.sch.ng/'),
(27, N'Federal Government Girls'' College, Potiskum', 'FGGC Potiskum ', N'Yobe', N'https://fggcpotiskum.sch.ng/'),
(28, N'Federal Government College, Biliri', 'FGC Biliri ', N'Gombe', N'https://fgcbilliri.sch.ng/'),
(29, N'Federal Government Girls'' College, Bajoga', 'FGGC Bajoga ', N'Gombe', N'https://fggcbajoga.sch.ng/'),
(30, N'Federal Government College, Ikot-Ekpene', 'FGC Ikot-Ekpene ', N'Akwa Ibom', N'https://fgcikotekpene.sch.ng/'),
(31, N'Federal Government Girls'' College, Ikot-Obio-Itong', 'FGGC Ikot-Obio-Itong ', N'Akwa Ibom', N'https://fggcikotobioitong.sch.ng/'),
(32, N'Federal Science and Technical College, Uyo', 'FSTC Uyo ', N'Akwa Ibom', N'https://fstcuyo.sch.ng/'),
(33, N'Federal Government College, Ikom', 'FGC Ikom ', N'Cross River', N'https://fgcikom.sch.ng/'),
(34, N'Federal Science College, Ogoja', 'FSC Ogoja', N'Cross River', N'https://fggccalabar.sch.ng/'),
(35, N'Federal Government Girls'' College, Calabar', 'FGGC Calabar', N'Cross River', N'https://fscogoja.sch.ng/'),
(36, N'Federal Government College, Warri', 'FGC Warri ', N'Delta', N'https://fgcwarri.sch.ng/'),
(37, N'Federal Government Girls'' College, Ibusa', 'FGGC Ibusa ', N'Delta', N'https://fggcibusa.sch.ng/'),
(38, N'Federal Government College, Ibillo', 'FGC Ibillo ', N'Edo', N'https://fgcibillo.sch.ng/'),
(39, N'Federal Government Girls'' College, Benin', 'FGGC Benin ', N'Edo', N'https://fggcbenin.sch.ng/'),
(40, N'Federal Science and Technical College, Uromi', 'FSTC Uromi ', N'Edo', N'https://fstcuromi.sch.ng/'),
(41, N'Federal Government College, Port-Harcourt', 'FGC Port-Harcourt ', N'Rivers', N'https://fgcportharcourt.sch.ng/'),
(42, N'Federal Government Girls'' College, Abuloma', 'FGGC Abuloma ', N'Rivers', N'https://fggcabuloma.sch.ng/'),
(43, N'Federal Science and Technical College, Ahoada', 'FSTC Ahoada ', N'Rivers', N'https://fstcahoada.sch.ng/'),
(44, N'Federal Government College, Odi', 'FGC Odi ', N'Bayelsa', N'https://fgcodi.sch.ng/'),
(45, N'Federal Government Girls'' College, Imiringi', 'FGGC Imiringi ', N'Bayelsa', N'https://fggcimiringi.sch.ng/'),
(46, N'Federal Science and Technical College, Tungbo', 'FSTC Tungbo ', N'Bayelsa', N'https://fstc.tungbo.sch.ng/'),
(47, N'Federal Government College, Vandeikya', 'FGC Vandeikya ', N'Benue', N'https://fgcvandeikya.sch.ng/'),
(48, N'Federal Government Girls'' College, Gboko', 'FGGC Gboko ', N'Benue', N'https://fggcgboko.sch.ng/'),
(49, N'Federal Government College, Otobi', 'FGC Otobi ', N'Benue', N'https://fgcotobi.sch.ng/'),
(50, N'Federal Science and Technical College, Otukpo', 'FSTC Otukpo ', N'Benue', N'https://fstcotukpo.sch.ng/'),
(51, N'Federal Government College, Ugwolawo', 'FGC Ugwolawo ', N'Kogi', N'https://fgcugwolawo.sch.ng/'),
(52, N'Federal Government Girls'' College, Kabba', 'FGGC Kabba ', N'Kogi', N'https://fggckabba.sch.ng/'),
(53, N'Federal Science and Technical College, Ogugu', 'FSTC Ogugu ', N'Kogi', N'https://fstcogugu.sch.ng/'),
(54, N'Federal Government College, Ilorin', 'FGC Ilorin ', N'Kwara', N'https://fgcilorin.sch.ng/'),
(55, N'Federal Government Girls'' College, Omu-Aran', 'FGGC Omu-Aran ', N'Kwara', N'https://fggcomuaran.sch.ng/'),
(56, N'Federal Government College, Minna', 'FGC Minna ', N'Niger', N'https://fgcminna.sch.ng/'),
(57, N'Federal Government Girls'' College, Bida', 'FGGC Bida ', N'Niger', N'https://fggcbida.sch.ng/'),
(58, N'Federal Government College, New-Bussa', 'FGC New-Bussa ', N'Niger', N'https://fggcnewbussa.sch.ng/'),
(59, N'Federal Science and Technical College, Shiroro', 'FSTC Shiroro ', N'Niger', N'https://fstckutashiroro.sch.ng/'),
(60, N'Federal Government College, Jos', 'FGC Jos ', N'Plateau', N'https://fgcjos.sch.ng/'),
(61, N'Federal Government Girls'' College, Langtang', 'FGGC Langtang ', N'Plateau', N'https://fggclangtang.sch.ng/'),
(62, N'Federal Government College, Kwali', 'FGC Kwali ', N'FCT', N'https://fgckwali.sch.ng/'),
(63, N'Federal Government Girls'' College, Bwari', 'FGGC Bwari ', N'FCT', N'https://fggcbwari.sch.ng/'),
(64, N'Federal Government Girls'' College, Abaji', 'FGGC Abaji ', N'FCT', N'https://fggcabaji.sch.ng/'),
(65, N'Federal Government Boys'' College, Garki', 'FGBC Garki ', N'FCT', N'https://fgbcabuja.sch.ng/'),
(66, N'Federal Government College, Rubochi', 'FGC Rubochi ', N'FCT', N'https://fgcrubochi.sch.ng/'),
(67, N'Federal Science and Technical College, Orozo', 'FSTC Orozo ', N'FCT', N'https://fstcorozo.sch.ng/'),
(68, N'Federal Government College, Keffi (Boys &Girls)', 'FGC Keffi', N'Nasarawa', N'https://fgckeffi.sch.ng/'),
(69, N'Federal Government Girls'' College, Keana', 'FGGC Keana ', N'Nasarawa', N'https://fggckeana.sch.ng/'),
(70, N'Federal Science and Technical College, Doma', 'FSTC Doma ', N'Nasarawa', N'https://fstcdoma.sch.ng/'),
(71, N'King’s College, Lagos', 'King''s College', N'Lagos', N'https://kingscollegelagos.sch.ng/'),
(72, N'Federal Government College, Lagos', 'FGC Lagos ', N'Lagos', N'https://fgclagos.sch.ng/'),
(73, N'Queen’s College, Lagos', 'Queen’s College', N'Lagos', N'https://queenscollegelagos.sch.ng/'),
(74, N'Federal Science and Technical College, Yaba', 'FSTC Yaba ', N'Lagos', N'https://fstcyaba.sch.ng/'),
(75, N'Federal Government College, Odogbolu', 'FGC Odogbolu ', N'Ogun', N'https://fgcodogbolu.sch.ng/'),
(76, N'Federal Government Girls'' College, Shagamu', 'FGGC Shagamu ', N'Ogun', N'https://www.fggcsagamu.sch.ng/'),
(77, N'Federal Science and Technical College, Ijebu Mushin', 'FSTC Ijebu Mushin ', N'Ogun', N'https://fstcijebuimusin.sch.ng/'),
(78, N'Federal Government College, Idoani', 'FGC Idoani ', N'Ondo', N'https://fgcidoani.sch.ng/'),
(79, N'Federal Government Girls'' College, Akure', 'FGGC Akure ', N'Ondo', N'https://fggcakure.sch.ng/'),
(80, N'Federal Science and Technical College, Ikare-Akoko', 'FSTC Ikare-Akoko ', N'Ondo', N'https://fstcikare.sch.ng/'),
(81, N'Federal Government College, Ikirun', 'FGC Ikirun ', N'Osun', N'https://fgcikirun.sch.ng/'),
(82, N'Federal Government Girls'' College, Ipetumodu', 'FGGC Ipetumodu ', N'Osun', N'https://fggcipetumodu.sch.ng/'),
(83, N'Federal Science and Technical College, Ilesa', 'FSTC Ilesa ', N'Osun', N'https://fstcilesa.sch.ng/'),
(84, N'Federal Government College, Ogbomoso', 'FGC Ogbomoso ', N'Oyo', N'https://fgcogbomoso.sch.ng/'),
(85, N'Federal Government Girls'' College, Oyo', 'FGGC Oyo ', N'Oyo', N'https://fggcoyo.sch.ng/'),
(86, N'Federal Science and Technical College, Igangan', 'FSTC Igangan ', N'Oyo', N'https://fstcigangan.sch.ng/'),
(87, N'Federal Government College, Ikole-Ekiti', 'FGC Ikole-Ekiti ', N'Ekiti', N'https://fgcikoleekiti.sch.ng/'),
(88, N'Federal Government Girls'' College, Efon-Alaye', 'FGGC Efon-Alaye ', N'Ekiti', N'https://fggcefonalaaye.sch.ng/'),
(89, N'Federal Science and Technical College, Usi-Ekiti', 'FSTC Usi-Ekiti ', N'Ekiti', N'https://fstcusiekiti.sch.ng/'),
(90, N'Federal Government College, Kiyawa', 'FGC Kiyawa ', N'Jigawa', N'https://fgckiyawa.sch.ng/'),
(91, N'Federal Government Girls'' College, Kazaure', 'FGGC Kazaure ', N'Jigawa', N'https://fggckazaure.sch.ng/'),
(92, N'Federal Science and Technical College, Mallam Madori-Birniwa', 'FSTC Mallam Madori-Birniwa ', N'Jigawa', N'#N/A'),
(93, N'Federal Government College, Kaduna', 'FGC Kaduna ', N'Kaduna', N'https://fgckaduna.sch.ng/'),
(94, N'Federal Government Girls'' College, Zaria', 'FGGC Zaria ', N'Kaduna', N'https://fggczaria.sch.ng/'),
(95, N'Federal Science and Technical College, Kafanchan', 'FSTC Kafanchan ', N'Kaduna', N'https://fstckafanchan.sch.ng/'),
(96, N'Federal Government College, Kano', 'FGC Kano ', N'Kano', N'https://fgckano.sch.ng/'),
(97, N'Federal Government Girls'' College, Min-Jibir', 'FGGC Min-Jibir ', N'Kano', N'https://fggcminjibir.sch.ng/'),
(98, N'Federal Science and Technical College, Ganduje', 'FSTC Ganduje ', N'Kano', N'https://fggcminjibirsch.ng/'),
(99, N'Federal Government College, Daura', 'FGC Daura ', N'Katsina', N'https://fggcdaura.sch.ng/'),
(100, N'Federal Government Girls'' College, Bakori', 'FGGC Bakori ', N'Katsina', N'https://fggcbakori.sch.ng/'),
(101, N'Federal Science and Technical College, Dayi', 'FSTC Dayi ', N'Katsina', N'https://fggcdayi.sch.ng/'),
(102, N'Federal Government College, Birnin-Yauri', 'FGC Birnin-Yauri ', N'Kebbi', N'https://fggcyauri.sch.ng/'),
(103, N'Federal Government Girls'' College, Gwandu', 'FGGC Gwandu ', N'Kebbi', N'https://fggcgwandu.sch.ng/'),
(104, N'Federal Science and Technical College, Zuru', 'FSTC Zuru ', N'Kebbi', N'https://fggczuru.sch.ng/'),
(105, N'Federal Government College, Sokoto', 'FGC Sokoto ', N'Sokoto', N'https://https//fscsokoto.sch.ng/'),
(106, N'Federal Science College, Sokoto', 'FSC Sokoto', N'Sokoto', N'https://https//fscsokoto.sch.ng/'),
(107, N'Federal Government Girls'' College, Tambuwal', 'FGGC Tambuwal ', N'Sokoto', N'https://fggctambuwal.sch.ng/'),
(108, N'Federal Government Girls'' College, Gusau', 'FGGC Gusau ', N'Zamfara', N'https://fggcgusau.sch.ng/'),
(109, N'Federal Government College, Anka', 'FGC Anka ', N'Zamfara', N'https://fggcanka.sch.ng/')
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

IF @@TRANCOUNT>0 COMMIT TRANSACTION
SET NOEXEC OFF
GO