--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 7.0.249.0
-- Product home page: https://www.devart.com/dbforge/sql/studio
-- Script date 04/03/2025 16:01:51
-- Server version: 16.00.1000
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT, XACT_ABORT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS OFF
GO

BEGIN TRANSACTION

--
-- Inserting data into table fedeco.dbo.StateDim
--
INSERT fedeco.dbo.StateDim(id, state, capital, geo_political_zone) VALUES
(1, N'Abia', N'Umuahia', N'South-East'),
(2, N'Adamawa', N'Yola', N'North-East'),
(3, N'Akwa Ibom', N'Uyo', N'South-South'),
(4, N'Anambra', N'Awka', N'South-East'),
(5, N'Bauchi', N'Bauchi', N'North-East'),
(6, N'Bayelsa', N'Yenagoa', N'South-South'),
(7, N'Benue', N'Makurdi', N'North-Central'),
(8, N'Borno', N'Maiduguri', N'North-East'),
(9, N'Cross River', N'Calabar', N'South-South'),
(10, N'Delta', N'Asaba', N'South-South'),
(11, N'Ebonyi', N'Abakaliki', N'South-East'),
(12, N'Edo', N'Benin City', N'South-South'),
(13, N'Ekiti', N'Ado-Ekiti', N'South-West'),
(14, N'Enugu', N'Enugu', N'South-East'),
(15, N'FCT', N'Abuja', N'North-Central'),
(16, N'Gombe', N'Gombe', N'North-East'),
(17, N'Imo', N'Owerri', N'South-East'),
(18, N'Jigawa', N'Dutse', N'North-West'),
(19, N'Kaduna', N'Kaduna', N'North-West'),
(20, N'Kano', N'Kano', N'North-West'),
(21, N'Katsina', N'Katsina', N'North-West'),
(22, N'Kebbi', N'Birnin Kebbi', N'North-West'),
(23, N'Kogi', N'Lokoja', N'North-Central'),
(24, N'Kwara', N'Ilorin', N'North-Central'),
(25, N'Lagos', N'Ikeja', N'South-West'),
(26, N'Nasarawa', N'Lafia', N'North-Central'),
(27, N'Niger', N'Minna', N'North-Central'),
(28, N'Ogun', N'Abeokuta', N'South-West'),
(29, N'Ondo', N'Akure', N'South-West'),
(30, N'Osun', N'Oshogbo', N'South-West'),
(31, N'Oyo', N'Ibadan', N'South-West'),
(32, N'Plateau', N'Jos', N'North-Central'),
(33, N'Rivers', N'Port Harcourt', N'South-South'),
(34, N'Sokoto', N'Sokoto', N'North-West'),
(35, N'Taraba', N'Jalingo', N'North-East'),
(36, N'Yobe', N'Damaturu', N'North-East'),
(37, N'Zamfara', N'Gusau', N'North-West')
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

IF @@TRANCOUNT>0 COMMIT TRANSACTION
SET NOEXEC OFF
GO